spring: 
  api: 
    payment: 
      context-path: /CorporateCurrentAccount/{corporatecurrentaccountId}/Retrieve
      hosturl: /payment
      jolt-filename: payment397279-jolt.json
    paymentexecution: 
      context-path: /PaymentExecution/Initiate
      hosturl: /payment
      jolt-filename: paymentexecution653821-jolt.json
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${mysql_pwd}
    url: jdbc:mysql://${mysql_url}:3306/camunda
    username: ${mysql_user}
